### ISSUE TITLE
need to update line version which supported chef 12

### ISSUE THREAD

**Issue by yogeshrathore15** [atomic-penguin/cookbook-nfs#107]
Hi team,
we are using NFS cookbook as a dependency in our cookbook , it downloading during runtime but we are supporting chef 12 but NFS depends Line latest version which support Chef 13 
how I can change the line version or 
could you please update acoordingly

**Comment by MarkGibbons** [comment]
Line 2.0.1 was just released to supermarket.chef.io has been tested with chef 12.13.37. It passes the integration tests.  I plan to use it on servers running chef-client 12.  Line 2.0.1 doesn't have chef spec matchers. Those were removed as  unneeded in chef 13 with current versions of chef spec.

**Comment by atomic-penguin** [comment]
I need more information on how the version constraints are affecting you @yogeshrathore15?

Can you propose a version constraint for line that will work for you, so that I can review it for compatibility?

**Comment by GitBytes** [comment]
IMHO a simple change to `>= 1.0.6` would be sufficient. Let the end user lock down the version if they desire. You have effectively locked the community to the `1.0.x` versions of `line`. `2.x` of `line` has been out there for two months now. Thanks in advance!

Bump

**Comment by atomic-penguin** [comment]
Fixed in v2.6.0
