### ISSUE TITLE
duplicate entries added to /etc/exports

### ISSUE THREAD

**Issue by bish0polis** [atomic-penguin/cookbook-nfs#110]
This doesn't look like a dupe of #48 .  

I have a new host.  I've included nfs::server and I have an nfs_export stanza for /home .  Unfortunately, it's adding a new entry every time.   The first run is awesome:

````
  * nfs_export[/home] action create
    * execute[exportfs] action nothing (skipped due to action :nothing)
    * file[/etc/exports] action create
      - update content in file /etc/exports from e3b0c4 to 6c8ca7
      --- /etc/exports  2018-06-18 01:39:07.760976697 -0400
      +++ /etc/.chef-exports20180618-8749-2l9dac        2018-06-18 01:39:44.888492248 -0400
      @@ -1 +1,2 @@
      +/home 10.1.1.0/24(rw,sync,root_squash)
    * execute[exportfs] action run
      - execute exportfs -ar
````
So far, very cool.

Run it again:
````
[root@orbit ~]# !!
:
  * nfs_export[/home] action create
    * execute[exportfs] action nothing (skipped due to action :nothing)
    * append_if_no_line[export /home] action edit
      * file[/etc/exports] action create
        - update content in file /etc/exports from 6c8ca7 to e80981
        - suppressed sensitive resource

    * execute[exportfs] action run

      ================================================================================
      Error executing action `run` on resource 'execute[exportfs]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of exportfs -ar ----
      STDOUT:
      STDERR: exportfs: duplicated export entries:
      exportfs:         10.1.1.0/24:/home
      exportfs:         10.1.1.0/24:/home
      ---- End output of exportfs -ar ----
      Ran exportfs -ar returned 1
:
:
````

I'm not modding that file or touching it outside of the LWRP, so I'm confused as to what's even triggering the newline.

This one demands a custom template as mentioned in #48 , I guess, but I'm delighted to use the nfs::server recipe for as much as it does.

**Comment by MarkGibbons** [comment]
The line cookbook is trying to match "/home 10.1.1.0/24(rw,sync,root_squash)\n" against records where the trailing newline has been removed. It won't match and the line will always be appended. In the export provider 'export_line = "#{new_resource.directory} #{new_resource.network}(#{ro_rw},#{sync_async}#{options})\n"'  doesn't need to \n on the line to be appended to the file.  Line::append_if_no_line was rewritten and that's a use case that wasn't tested for.

**Comment by MarkGibbons** [comment]
I opened an issue in the line cookbook.  It shouldn't accept the input with \n in the line.
https://github.com/sous-chefs/line-cookbook/issues/113

**Comment by bish0polis** [comment]
Thanks for opening that ticket, Mark.  I should mention that I'm using Enterprise Linux (RHEL, OEL, etc) and I can't test ubuntu so I'd have to go on faith it's the same behaviour.  

I'll watch ticket the other ticket too.  Thanks again.

**Comment by raghureddy45** [comment]
I am Having the same issue. :(
Its keep on adding duplicate entries to /etc/exports

**Comment by MarkGibbons** [comment]
Could you tell me:
Which version of the line cookbook you are using?
Which version of the nfs cookbook you are using?
The code for the resource used that causes the problem?

I'm having trouble reproducing the problem.

**Comment by raghureddy45** [comment]
## versions
chef-client version:  `12.14.60`
nfs cookbook version: `2.3.1`
line cookbook version: `2.0.1`

## Error
```ruby 
* append_if_no_line[export /sapmnt/SB1] action edit
      * file[/etc/exports] action create
        - update content in file /etc/exports from 7752f1 to 5e708f
        - suppressed sensitive resource
    
    * execute[exportfs] action run
      
      ================================================================================
      Error executing action `run` on resource 'execute[exportfs]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of exportfs -ar ----
      STDOUT: 
      STDERR: exportfs: duplicated export entries:
      exportfs: 	10.217.21.92:/sapmnt/SB1
      exportfs: 	10.217.21.92:/sapmnt/SB1
```
## Code that causing the issue 
```ruby
    nfs_export "/sapmnt/#{sid}" do
      network client_ips
      writeable true
      sync true
      options ['no_root_squash']
    end
```

I have this entry already in /etc/exports instead of skipping, it is appending same line again.

**Comment by MarkGibbons** [comment]
@raghureddy45 Does it create a third identical entry or just a second? Does it append a line with every chef-client run?

**Comment by raghureddy45** [comment]
It will append a line with every chef-client run.!!

**Comment by MarkGibbons** [comment]
Line 2.0.2 was released that fixes the issue from line 2.0.1.

**Comment by bish0polis** [comment]
Great news!  I'll pull and re-test once I'm back in to the keyboard (wed).

**Comment by raghureddy45** [comment]
Thanks @MarkGibbons,  working fine now.! Really appreciate your effort.

**Comment by bish0polis** [comment]
Yeah, it's looking good with 2.0.2 .  Thanks !
