### ISSUE TITLE
/sbin/start rpcbind returned 1, expected 0

### ISSUE THREAD

**Issue by luntzel** [atomic-penguin/cookbook-nfs#40]
This probably has to do with the fact that I'm running this on Ubuntu Lucid (10.04). I tried playing around with the service resource init_command but no love there. Any advice here would be much appreciated. Thanks!

nfs cookbook version 2.0.0
Chef: 11.14.2
Ubuntu 10.04

https://gist.github.com/luntzel/4e9dcb0b2137266806ce

**Comment by atomic-penguin** [comment]
Honestly the provider mapping in Chef is getting an overhaul, so I don't know if the cookbook is broken or its an ephemeral bug in Chef 12.  The provider mapping search is an ugly hack that might be able to go away in this cookbook after Chef 12.1.  Its probably the problem in this case, and you could override the service_provider attributes with the appropriate provider [here](https://docs.chef.io/resource_service.html#providers).

The more information about the services you can provide, the better it will help me to assist.
