### ISSUE TITLE
_idmap recipe on debian also installs nfs-kernel-server

### ISSUE THREAD

**Issue by stevenolen** [atomic-penguin/cookbook-nfs#43]
when selecting nfs::client4 for NFSv4 client support on ubuntu/debian this recipe also runs the _idmap recipe (which makes sense to me, idmapd is needed) but in this line:

https://github.com/atomic-penguin/cookbook-nfs/blob/master/recipes/_idmap.rb#L22

nfs-kernel-server is also installed, which should only be required for the nfs server, not the client.  Perhaps I'm missing something, but I've been running an NFSv4 setup for quite some time on ubuntu without nfs-kernel-server installed on the clients.  Perhaps this should be removed, maybe the reasoning clarified or at least the installation of this package abstracted to an attribute so someone can opt of out nfs-kernel-server installation on their nfs client.

Thanks for the cookbook!

**Comment by atomic-penguin** [comment]
@stevenolen I don't normally use debian/ubuntu in production.  That line was carried over from an older version of the cookbook.  At some point I needed (or believed this was needed) that idmap was in nfs-kernel-server.  Note when that dependency was added, idmap was not a separate recipe.

**Comment by stevenolen** [comment]
Ah great! based on ubuntu 12.04:

```
root@test:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"

root@test:~# dpkg -S /etc/init.d/idmapd 
nfs-common: /etc/init.d/idmapd
```

and a number of config links for nfs client on debian/ubuntu:
http://www.server-world.info/en/note?os=Debian_7.0&p=nfs&f=2
https://help.ubuntu.com/community/NFSv4Howto

idmapd should actually come with the nfs-common package.  Would you like me to submit a pull request to modify this line, happy to if that fits your dev flow best!
