### ISSUE TITLE
idmapd not starting on SLES 11 SP3

### ISSUE THREAD

**Issue by vgirnet** [atomic-penguin/cookbook-nfs#45]
ERROR: service[idmap] (nfs::_idmap line 31) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '6'
---- Begin output of /sbin/service nfs start ----
STDOUT: Not starting NFS client services - no NFS found in /etc/fstab:
STDERR: ..unused
---- End output of /sbin/service nfs start ----
Ran /sbin/service nfs start returned 6

NFS service is not finding any NFS mount points in /etc/fstab, it consider NFS being useless, and exit with error. 
However, if adding 'NFS_START_SERVICES=yes' to '/etc/sysconfig/nfs' file, service starts successfully. 

This is the way how init script is written for SLES 11 SP 3. 

Can you add the line, please?
To /etc/sysconfig/nfs, 'suse' section
NFS_START_SERVICES=yes

Thanks,
Vladimir

**Comment by atomic-penguin** [comment]
Could you add the line to the template and pull request it, please?  There isn't a public SUSE basebox I can use to quickly test this with test-kitchen.

**Comment by atomic-penguin** [comment]
Released in 2.1.0
