### ISSUE TITLE
Question: firewall rules

### ISSUE THREAD

**Issue by StFS** [atomic-penguin/cookbook-nfs#50]
Hi.

Does anybody have a recommended way to handle firewall issues with this recipe? It seems that there are a lot of different options out there (firewalld and iptables for example) and on top of that I'm not a 100% sure what needs to be opened up exactly after this recipe has run.

Currently I'm trying out something like this for iptables (depends on the simple_iptables cookbook):

``` ruby
simple_iptables_rule "db-port" do
  rule ["--proto tcp --dport #{node.nfs.port.statd}", "--proto udp --dport #{node.nfs.port.statd}", 
    "--proto tcp --dport #{node.nfs.port.mountd}", "--proto udp --dport #{node.nfs.port.mountd}",
    "--proto tcp --dport #{node.nfs.port.lockd}", "--proto udp --dport #{node.nfs.port.lockd}",
    "--proto tcp --dport #{node.nfs.port.rquotad}", "--proto udp --dport #{node.nfs.port.rquotad}"]
  jump "ACCEPT"
end
```

And for firewalld I'm trying this:

``` ruby
firewalld_service 'nfs' do
    action :add
    zone   'public'
end
```

Then there is ufw and probably many others that could possibly be running. Please note that the code above has not been tested properly.

But my question is whether something like this should be a part of this cookbook? I'm not sure if there is a good way to find out 1) which firewall is running on a server and 2) whether that firewall is actually running or disabled. Any pointers on that would be appreciated.

Sorry about the open ended question here, I'm mostly just wondering whether anybody has experience worrying about firewall issues with NFS using this cookbook.

**Comment by atomic-penguin** [comment]
> But my question is whether something like this should be a part of this cookbook?

I have never really been satisfied with any of the publicly available community iptables/firewall cookbooks.  Most people I've seen use either a fork of 0.14.0 iptables, or their own organizational firewall cookbook.  I also have no interest in maintaining and testing support for iptables, ufw, pf, ipf, and firewalld as it pertains to this use case.  However, I'm not opposed to including a sample recipe, or documentation for NFS firewall rules.

> on top of that I'm not a 100% sure what needs to be opened up exactly after this recipe has run.

The best way to figure that out is with a `netstat -lnp | less` on the host, and inventory what needs opened

```
# 192.0.2.0/24 CIDR is TEST-NET-1 reserved for documentation, replace with your own CIDR.
# Port 111 portmap.
# Portmap is bound to IANA reserved port 111, and tells NFS clients what ports the RPC services are bound on.
-A INPUT -p tcp -m tcp --dport 111 -s 192.0.2.0/24 --syn -j ACCEPT
-A INPUT -p udp -m udp --dport 111 -s 192.0.2.0/24 -j ACCEPT
# NFSD is bound to IANA reserved port 2049
-A INPUT -p tcp -m tcp --dport 2049 -s 192.0.2.0/24 --syn -j ACCEPT
-A INPUT -p udp -m udp --dport 2049 -s 192.0.2.0/24 -j ACCEPT
# STATD incoming/STATD outgoing/MOUNTD/LOCKD/RQUOTAD are not reserved.  This recipe uses static ports 32765-32769 so that a firewall policy can be adapted.
# NOTE: not all services may be used in all cases.
-A INPUT -p tcp -m tcp --dport 32765:32769 -s 192.0.2.0/24 --syn -j ACCEPT
-A INPUT -p udp -m udp --dport 32765:32769 -s 192.0.2.0/24 -j ACCEPT
```
