### ISSUE TITLE
Add a license file to the repo

### ISSUE THREAD

**Issue by mbrukman** [atomic-penguin/cookbook-nfs#51]
I see that the [README](https://github.com/atomic-penguin/cookbook-nfs/blob/master/README.md#license-and-author) states that the code is under the Apache license.

Would you mind adding a copy of the full [license text](http://www.apache.org/licenses/LICENSE-2.0.txt) to the repo to clarify?

Thanks!

**Comment by atomic-penguin** [comment]
Its my understanding that application of the Apache 2 license by reference alone, is permissible.  What is the cause for concern, or ambiguity?

> The 2.0 version of the Apache License was approved by the ASF in 2004. The goals of this license revision have been to reduce the number of frequently asked questions, to allow the license to be reusable without modification by any project (including non-ASF projects), **to allow the license to be included by reference instead of listed in every file**, to clarify the license on submission of contributions, to require a patent license on contributions that necessarily infringe the contributor's own patents, and to move comments regarding Apache and other inherited attribution notices to a location outside the license terms (the NOTICE file )."

Reference: https://www.apache.org/licenses/#2.0

**Comment by mbrukman** [comment]
Sorry, looks like I wasn't being clear.

What I meant was to add a complete copy of the Apache license in a `LICENSE.txt` file at the top-level of the repo, not including it into every file, which is what the bold text above indicates. For example, if you create a new GitHub repo and choose the Apache license, it will add a text file to the repo with the contents being the license text from here: http://www.apache.org/licenses/LICENSE-2.0.txt .

Right now, there's only a summary and reference to the license in the README, and there isn't a complete copy of the license in the repo, which means it's not self-contained, and according to GitHub, [legally ambiguous](https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository):

> Some projects only include a descriptive line in the project's README (e.g., "This projected is licensed under the terms of the MIT license."). **However, to avoid any potential ambiguity, it's best to include the license file with your project as well.**

(emphasis mine)

**Comment by mbrukman** [comment]
Thanks, @atomic-penguin!
