### ISSUE TITLE
Define dependencies better?

### ISSUE THREAD

**Issue by djcp** [atomic-penguin/cookbook-nfs#75]
Very useful, thanks!

We just had an issue where the `awscli` recipe depended on the `python` recipe, which then depended on any version of the `build-essential` recipe. `build-essential` then released 2.3.0 which included chef 12 specific syntax (causing a compile-time error), which then broke our deploys and was difficult to trace down.

I can see that [this depends on any version of line and sysctl](https://github.com/atomic-penguin/cookbook-nfs/blob/master/metadata.rb#L13-L14), can you tighten these dependencies up so there aren't any unpleasant surprises if these recipes release chef 12 only code?

I could submit a PR if you'd like.

**Comment by atomic-penguin** [comment]
Yes, please submit a PR with relevant dependency constraints that fixed your issue.

**Comment by atomic-penguin** [comment]
I have bumped up the dependency for line to `>= 2.0` in 2.6.0, and removed the dependency on `sysctl` 2.6.1.  Please re-open if this does not resolve your issue.
