### ISSUE TITLE
Is this cookbook abandoned?

### ISSUE THREAD

**Issue by dougalb** [atomic-penguin/cookbook-nfs#80]
It appears that this cookbook is getting very little attention and issues/PRs are not reviewed?

**Comment by joerocklin** [comment]
We're still using it - just lots of other things have been a higher priority. There are currently 0 open PRs that I see. Is there a particular issue that is a high priority one for you?

**Comment by dougalb** [comment]
Specifically https://github.com/atomic-penguin/cookbook-nfs/issues/79 and probably also https://github.com/atomic-penguin/cookbook-nfs/issues/76. Now that 16.04 LTS is the latest Ubuntu LTS release, there is a growing need for supporting that OS.

**Comment by joerocklin** [comment]
Personally, I would love to see us remove the `Provider` definitions completely and just say: if you want to run this cookbook on a particular platform, make sure your version of chef knows which provider is needed. @atomic-penguin may have different feelings about this.

**Comment by dougalb** [comment]
I would prefer that approach too.

**Comment by atomic-penguin** [comment]
@joerocklin cleaning up the provider mapping seems reasonable to me.
