### ISSUE TITLE
Deprecated features used

### ISSUE THREAD

**Issue by sspans** [atomic-penguin/cookbook-nfs#84]
With chef-12 the following warnings are reported because /etc/sysconfig/nfs is
listed in server and client templates

```
Deprecated features used!
  Cloning resource attributes for template[/etc/sysconfig/nfs] from prior resource (CHEF-3694)
Previous template[/etc/sysconfig/nfs]: /var/chef/cache/cookbooks/nfs/recipes/_common.rb:36:in `block in from_file'
Current  template[/etc/sysconfig/nfs]: /var/chef/cache/cookbooks/nfs/recipes/server.rb:26:in `from_file' at 1 location:
    - /var/chef/cache/cookbooks/nfs/recipes/server.rb:26:in `from_file'
```

**Comment by joerocklin** [comment]
Which version of Chef 12.x and which version of the cookbook are you using?

**Comment by sspans** [comment]
This is with chef 12.12.15 and cookbook version 2.2.8

**Comment by sspans** [comment]
I've reworked the pull somewhat to make it more reasonable.
Still not sure if this is the best solution, but it does solve the issue.

**Comment by sspans** [comment]
@joerocklin: Any chance to get #85 and #86 merged?

**Comment by atomic-penguin** [comment]
Merged
