### ISSUE TITLE
Race condition on Centos7 nfs-server

### ISSUE THREAD

**Issue by dougalb** [atomic-penguin/cookbook-nfs#89]
Seeing a pretty regular race condition since the latest updates for CentOS 7. Basically the cookbook is trying to set sysctl values before the nfs modules have been loaded, so they don't exist.

`Recipe: nfs::server
         * sysctl_param[fs.nfs.nlm_tcpport] action apply
         
         * execute[sysctl[fs.nfs.nlm_tcpport]] action run
           
           ================================================================================
           Error executing action `run` on resource 'execute[sysctl[fs.nfs.nlm_tcpport]]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '255'
           ---- Begin output of sysctl -w "fs.nfs.nlm_tcpport=32768" ----
           STDOUT: 
           STDERR: sysctl: cannot stat /proc/sys/fs/nfs/nlm_tcpport: No such file or directory
           ---- End output of sysctl -w "fs.nfs.nlm_tcpport=32768" ----
           Ran sysctl -w "fs.nfs.nlm_tcpport=32768" returned 255
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/sysctl/providers/param.rb
           
            21:     execute "sysctl[#{new_resource.key}]" do
            22:       command "sysctl -w \"#{new_resource.key}=#{new_resource.value}\""
            23:       notifies :run, 'ruby_block[save-sysctl-params]', :delayed
            24:     end
            25:     new_resource.updated_by_last_action(true)
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/sysctl/providers/param.rb:21:in `block in class_from_file'
           
           execute("sysctl[fs.nfs.nlm_tcpport]") do
             action [:run]
             retries 0
             retry_delay 2
             default_guard_interpreter :execute
             command "sysctl -w \"fs.nfs.nlm_tcpport=32768\""
             backup 5
             returns 0
             declared_type :execute
             cookbook_name "nfs"
           end
           
           Platform:
           ---------
           x86_64-linux
           
       Recipe: openssh::default
         * service[ssh] action restart
           - restart service service[ssh]
       Recipe: nfs::server
         * service[nfs-server] action restart
           - restart service service[nfs-server]
       
       Running handlers:
       [2016-08-31T23:44:36+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-08-31T23:44:36+00:00] ERROR: Exception handlers complete
       Chef Client failed. 65 resources updated in 06 minutes 12 seconds
       [2016-08-31T23:44:36+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-08-31T23:44:36+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-08-31T23:44:36+00:00] ERROR: execute[sysctl[fs.nfs.nlm_tcpport]] (/tmp/kitchen/cache/cookbooks/sysctl/providers/param.rb line 21) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '255'
       ---- Begin output of sysctl -w "fs.nfs.nlm_tcpport=32768" ----
       STDOUT: 
       STDERR: sysctl: cannot stat /proc/sys/fs/nfs/nlm_tcpport: No such file or directory
       ---- End output of sysctl -w "fs.nfs.nlm_tcpport=32768" ----
       Ran sysctl -w "fs.nfs.nlm_tcpport=32768" returned 255
       [2016-08-31T23:44:36+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)`

**Comment by dougalb** [comment]
Has this been fixed?

**Comment by atomic-penguin** [comment]
Probably, not.  Closed the wrong issue.
