### ISSUE TITLE
Invalid /etc/exports generated since v2.3.3

### ISSUE THREAD

**Issue by jperville** [atomic-penguin/cookbook-nfs#96]
I have a chef recipe which declares several NFS exports.

Before v2.3.3, my node would converge just fine.
After v2.3.3, the chef-run fails with the following message:

```
==> backends:     Mixlib::ShellOut::ShellCommandFailed
==> backends:     ------------------------------------
==> backends:     nfs_export[/srv/nfs-shared-2] (/tmp/vagrant-cache/chef/cookbooks/pm_environment/libraries/openshift3_nfs_export.rb line 32) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[exportfs] (/tmp/vagrant-cache/chef/cookbooks/nfs/providers/export.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> backends:     ---- Begin output of exportfs -ar ----
==> backends:     STDOUT: 
==> backends:     STDERR: exportfs: /etc/exports:1: syntax error: bad option list
==> backends:     ---- End output of exportfs -ar ----
==> backends:     Ran exportfs -ar returned 1
==> backends:     
==> backends:     Cookbook Trace:
```

Here is the generated `/etc/exports` on the node:

```sh
[root@backends ~]# cat /etc/exports
/srv/nfs-shared-1 192.168.33.0/24(rw,sync,no_root_squash,no_wdelay)/srv/nfs-shared-2 192.168.33.0/24(rw,sync,no_root_squash,no_wdelay)
```

Note that the two exports are incorrectly placed on the same line, instead of being placed on two different lines.

I believe that this regression is the consequence of #95, which was recently merged.

As a workaround, I will stick to v2.3.1 until this issue is fixed.

**Comment by atomic-penguin** [comment]
Thanks for the heads up, I pulled 2.3.3 from the supermarket.

**Comment by atomic-penguin** [comment]
@jperville My apologies, it regressed because my local tree wasn't clean.  I pushed a v2.4.1 to correct the issue.

**Comment by jperville** [comment]
Thank you very much for the quick fix.
